import { EXPLORE_DEEP_LINK_URL } from '../../lib/appConstants';

export const GINJA_ASSISTANCE_CONTENT = {
  eyebrow: 'GINJA ASSISTANCE',
  headline: 'Your assistant, wherever you message.',
  body: 'Tell Ginja what you need, answer a few natural questions, and turn the conversation into plans, reminders, places, and organised tasks.',
  channels: ['WhatsApp', 'SMS'],
  channelLine: 'Available on WhatsApp and SMS.',
  benefits: [
    {
      title: 'Capture anything instantly',
      body: 'Turn a simple message into a task, reminder, or plan.',
    },
    {
      title: 'Understand your day',
      body: 'Ask what is coming up, what is overdue, or what time you are free.',
    },
    {
      title: 'Move naturally into Ginja',
      body: 'When the next step needs more context, Ginja guides you into the right part of the app.',
    },
  ],
  cta: 'See how Ginja Assistance works',
  closing: 'Productivity should start the moment you have the thought — not when you remember to open an app.',
  phoneNote: 'The same connected experience is available through SMS/text.',
  conversation: {
    greeting: "Hey Alex, how's your day.  what can I help you with today?",
    birthdayRequest: 'I need to plan my girlfriend’s birthday.',
    birthdayQuestion: 'I’d love to help. When is her birthday?',
    birthdayDate: 'Next Saturday.',
    planTypeQuestion: 'What are you thinking?',
    planOptions: [
      { letter: 'A', label: 'Dinner' },
      { letter: 'B', label: 'Party' },
      { letter: 'C', label: 'Day out' },
      { letter: 'D', label: 'I’m not sure yet' },
    ],
    planTypeReply: 'A',
    peopleQuestion: 'Nice. How many people?',
    peopleReply: 'Just the two of us.',
    budgetQuestion: 'And what budget should I work with?',
    budgetReply: 'Around £150.',
    planIntro: 'Perfect. I’ve put together a simple birthday plan for you.',
    plan: {
      title: 'Birthday Dinner Plan',
      tasks: [
        'Book a romantic restaurant',
        'Buy flowers by Friday',
        'Pick up a birthday gift',
        'Leave home at 6:30 PM',
        'Dinner reservation at 7:30 PM',
      ],
      action: 'Add plan to Ginja',
      addedAction: 'Added to Ginja',
    },
    planAdded: 'Done. I’ve added the plan to Ginja and organised the tasks around your schedule.',
    exploreIntro: 'I also found a romantic restaurant nearby that fits the plan.',
    explore: {
      name: 'The Olive Room',
      rating: '4.8',
      distance: '1.2 miles',
      description: 'Romantic dining · Quiet garden setting',
      action: 'Open in Explore',
      href: EXPLORE_DEEP_LINK_URL,
    },
    reminderRequest: 'Remind me to buy flowers on Friday after work.',
    reminderResponse: 'Done. I’ll remind you Friday at 5:30 PM.',
    todayRequest: 'What do I have left today?',
    todayIntro: 'You have 3 tasks left today:',
    todayTasks: [
      { number: 1, title: 'Buy birthday card' },
      { number: 2, title: 'Confirm restaurant booking', status: 'overdue' },
      { number: 3, title: 'Order the cake', time: '7:00 PM' },
    ],
    taskInstructions: 'Reply with a task number, task name, or a command like ‘mark 2 done’ or ‘move the cake to tomorrow.’',
    completeRequest: 'Mark 2 done.',
    completeResponse: 'Done. You have 2 tasks left today.',
  },
};
